M48
; DRILL file {KiCad 9.0.7-1.fc43} date 2026-03-03T16:06:47-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-03T16:06:47-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-1.fc43
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.850
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.900
%
G90
G05
T1
X73.153Y-81.735
X77.335Y-64.34
X80.945Y-71.647
T2
X74.5Y-56.5
X74.5Y-77.0
T3
X77.96Y-86.5
X80.5Y-86.5
M30
